hybrid_bandit_ppo:
    run: PPO
    stop:
        timesteps_total: 300000
    checkpoint_at_end: True
    num_samples: 20
    config:
        evaluation_interval: 1
        # === Environment ===
        env: roshambo
        env_config:
            transitive_actions: 7
            cyclic_actions: 3
            num_contexts: 1
        # === PPO ===
        lambda: 0.95
        gamma: 0.99
        entropy_coeff: 0.0
        clip_param: 0.1
        lr: 0.0001
        kl_target: 0.01
        num_sgd_iter: 16
        sgd_minibatch_size: 32
        train_batch_size: 160
        rollout_fragment_length: 40
        batch_mode: complete_episodes