deep_sea_rnd_40:
    run: PPO_CURIOSITY
    stop:
        timesteps_total: 800000
    checkpoint_at_end: True
    num_samples: 10
    config:
        # === Environment ===
        horizon: 50
        env: openspiel
        env_config:
            game: deep_sea
            size: 40
        # === Curiosity ===
        model:
            custom_options: 
                weight: 2.0
                decay: 0.2
                burn_in: 1600
                delay: 800
                curiosity_module: RND
                curiosity_config:
                    fcnet_activation: relu
                    fcnet_hiddens: [256, 256]
                    fcnet_outputs: 32
                    agent_action: True
                    joint_action: False
        # === Intrinsic PPO ===
        intrinsic_gamma: 0.95
        intrinsic_lambda: 0.95
        num_agents: 1
        # === PPO ===
        lambda: 0.95
        gamma: 0.99
        entropy_coeff: 0.001
        clip_param: 0.1
        lr: 0.00001
        num_sgd_iter: 16
        sgd_minibatch_size: 32
        train_batch_size: 160
        rollout_fragment_length: 40
        batch_mode: complete_episodes