space_invaders_ppo:
    run: PPO
    stop:
        timesteps_total: 5000000
    checkpoint_freq: 200
    checkpoint_at_end: True
    num_samples: 4
    config:
        # === Environment ===
        env: gym_atari
        env_config:
            game: SpaceInvaders-v4
        # === PPO ===
        lambda: 0.95
        gamma: 0.99
        kl_coeff: 0.5
        entropy_coeff: 0.01
        clip_rewards: True
        clip_param: 0.1
        lr: 0.001
        num_sgd_iter: 16
        sgd_minibatch_size: 512
        train_batch_size: 4800
        rollout_fragment_length: 300
        num_envs_per_worker: 4
        batch_mode: truncate_episodes
        observation_filter: NoFilter
        vf_share_layers: true
        num_gpus: 1